### ISSUE TITLE
parcelJS v1.12.4 incompatible with nodeJS v14+

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/framework-2021#10]
## Problem
Under windows 10, NodeJS v14+, with parcel-bundler v1.12.4 as a dev dependency `npm run start` results in ` D:\dev\OR\kottans\framework-2021\index.js: Invalid Version: undefined`
error.

It's a [known issue](https://stackoverflow.com/questions/66450445/parceljs-bundling-error-favicon-ico-invalid-version-undefined).

## Solution
Pin parcel-bundler version as 1.12.3 in dev-dependecies

**Comment by nktssh** [comment]
Resolved in #9
