### ISSUE TITLE
framework/element: Add className property handling 

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/framework-2021#35]
**Problem**:
`createElement` doesn't handle tags' `className` attribute.

**Solution**:
If `className` is a string then => split at spaces.
Then `element.classList.add(...classNamesList)`

**Comment by mustbefail** [comment]
is this task already taken? wanted to work on it

**Comment by OleksiyRudenko** [comment]
@mustbefail sorry, taken. Wanted this and adjacent issues to be closed by tomorrow's AMA

**Comment by mustbefail** [comment]
ok, np

**Comment by mustbefail** [comment]
is there a task that I can join?

**Comment by OleksiyRudenko** [comment]
@mustbefail sorry, not at the moment. Will keep the classroom posted of new tasks if there gonna be any

**Comment by OleksiyRudenko** [comment]
Resolved by 13576f7
